language: cpp
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y clang-3.5 ninja-build
  - python ./build/depot_tools/download_from_google_storage.py -b chromium-gn -s ./build/util/gn/gn.sha1
before_script:
  - ./build/util/gn/gn gen out
script: 
  - ninja -C out