sudo: false
dist: trusty
language: generic
addons:
    apt:
        sources:
          - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main"
            key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
          - sourceline: "deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty main"
          - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
          - sourceline: "deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
        packages:
          - "clang-4.0" 
          - "lldb-4.0" 
          - "lld-4.0"
          - "nasm"
          - "python2.7"
          - "python2.7-dev"
          - "ninja-build"
install:
  - "make -C tools/gn"
before_script:
  - tools/gn/out/Release/gn gen out 
script:
  - ninja -C out
