sudo: false
dist: trusty
language: generic
addons:
    apt:
        sources:
          - llvm-toolchain-trusty-4.0
          - sourceline: "ppa:ricotz/toolchain"
        packages:
          - "clang-4.0"
          - "lldb-4.0"
          - "lld-4.0"
          - "nasm"
          - "python2.7"
          - "ninja-build"
before_install:
  - mkdir -p $HOME/.toolchain
  - ln -s `which clang-4.0` $HOME/.toolchain/clang
  - ln -s `which clang++-4.0` $HOME/.toolchain/clang++
  - export PATH=$HOME/.toolchain:$PATH
install:
  - curl -L https://github.com/twrl/generate-ninja/releases/download/r2/gn > $HOME/.toolchain/gn
  - chmod +x $HOME/.toolchain/gn
before_script:
  - gn gen out
script:
  - ninja -C out -k 10 -v
after_success:
  #- readelf -aW out/kernel | c++filt -t
  - objdump -xtrR out/image/EFI/Conurbation/{jonessvc.efi,jones.efi,kernel} | c++filt -t
