language: cpp
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq clang-3.7 ninja-build nasm
  - python ./build/depot_tools/download_from_google_storage.py -b chromium-gn -s ./build/tools/gn.sha1
before_script:
  - ./build/tools/gn gen build/out
script:
  - ninja -C out
