sudo: required
dist: trusty
language: generic
addons:
    apt:
        sources:
          - sourceline: "deb http://httpredir.debian.org/debian sid main"
            #key_url: "http://llvm.org/apt/llvm-snapshot.gpg.key"
        packages:
          - clang-3.8
          - ninja-build
          - nasm
          - gnu-efi 
          - binutils
install:
  - python ./build/depot_tools/download_from_google_storage.py -b chromium-gn -s ./build/tools/gn.sha1
before_script:
  - ./build/tools/gn gen build/out
script:
  - ninja -C build/out
